# Shared logging/guard helpers for the maintenance scripts in bin/.
# Scripts are symlinked into ~/.local/bin and locate this file via ${0:A},
# which resolves the symlink back into the repo.

dot_update_colors() {
  autoload -U colors
  colors
}

dot_update_log() {
  print -P "%F{yellow}==>%f $1"
}

dot_update_done() {
  print -P "%F{green}==>%f $1"
}

dot_update_fail() {
  print -u2 -P "%F{red}==>%f $1"
  return 1
}

dot_update_require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    dot_update_fail "$1 is required."
    return 1
  }
}

# Regenerate the modular brew manifests (Brewfile.taps/.formulae/.casks/.mas)
# from the live system state. No canonical Brewfile is kept: the dump goes
# to a temp file and only the split modules are written. vscode extension
# entries are intentionally dropped (VS Code Settings Sync owns those).
dot_update_refresh_brew_manifests() {
  emulate -L zsh
  setopt no_unset pipefail

  local modules_dir="${1:?usage: dot_update_refresh_brew_manifests <modules-dir>}"
  local header="# Auto-generated by the update scripts (brewup/brewdel/caskup). Do not edit."
  local tmp_dump kind outfile

  mkdir -p "$modules_dir" || {
    dot_update_fail "Failed to create modules dir: $modules_dir"
    return 1
  }
  tmp_dump="$(mktemp)" || {
    dot_update_fail "mktemp failed."
    return 1
  }

  dot_update_log "Dumping brew state..."
  brew bundle dump --describe --force --file "$tmp_dump" || {
    dot_update_fail "brew bundle dump failed."
    rm -f "$tmp_dump"
    return 1
  }

  # Each entry keeps the description comment --describe put right above it.
  for kind in tap brew cask mas; do
    case "$kind" in
      tap)  outfile="$modules_dir/Brewfile.taps" ;;
      brew) outfile="$modules_dir/Brewfile.formulae" ;;
      cask) outfile="$modules_dir/Brewfile.casks" ;;
      mas)  outfile="$modules_dir/Brewfile.mas" ;;
    esac
    {
      print -r -- "$header"
      print
      awk -v k="^$kind " '
        /^#/ { pending = $0; next }
        $0 ~ k { if (pending != "") print pending; print; pending = ""; next }
        { pending = "" }
      ' "$tmp_dump"
    } > "$outfile" || {
      dot_update_fail "Failed writing $outfile"
      rm -f "$tmp_dump"
      return 1
    }
  done

  rm -f "$tmp_dump"
  dot_update_done "Modular brew manifests written to $modules_dir."
}
