# Don't print a new line at the start of the prompt
add_newline = false

format = """$username@$hostname$directory$python$git_branch$git_status
${custom.uptime}$time$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[git_branch]
symbol = " "
truncation_length = 8
truncation_symbol = ".../"

[python]

[directory]
truncation_length = 0
truncation_symbol = ".../"
home_symbol = " "
style = "green"
format = "[$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
min_time = 500
format = "took [$duration]($style)"

[time]
disabled = false
style = "red"
time_format = "%H:%M"
format = "[$time]($style) "

[username]
show_always = true
style_user = "yellow"
style_root = "red bold"

format = "[$user]($style)"
[hostname]
ssh_only = false
style = "blue"
format = "[$hostname]($style) "

[custom.uptime]
when = "true"
command = "if hash guptime 2>/dev/null; then guptime; else uptime; fi | awk '{print $3}'| sed 's/,//g'"
style = "cyan"
shell = "zsh"
format = "[$output]($style) "
